### ISSUE TITLE
append() does not work for dictionary

### ISSUE THREAD

**Issue by tgib23** [mapr-demos/python-bindings#18]
I expect my code would work because the doc says
```
m.append(“field”, value) Append the specified field to the specified value which can be scalar, a list or a dict.
```

code
```py3
from maprdb import connect, Document, Mutation
connection = connect()
table_path = "/user/mapr/db/python-binding3"
table = None

if connection.exists(table_path):
    table = connection.get(table_path)
else:
    table = connection.create(table_path)

document1_key = "test"
document1 = Document({'_id':document1_key,
                      'other':{'a1':'a2', 'b1':'b2'}})

table.insert_or_replace(document1)

mutation1 = Mutation()
mutation1.append('other', {'c1':'c2'})

table.update(document1_key, mutation1)
table.flush()
```

results in TypeErro

```shell
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/maprdb/utils.py", line 98, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/maprdb/mutation.py", line 89, in append
    self.java_mutation = self.java_mutation.append(field_name, python_to_java_cast(value))
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 18, in <module>
    mutation1.append('other', {'c1':'c2'})
  File "/usr/lib/python3.3/site-packages/maprdb/utils.py", line 104, in wrapper
    raise TypeError(str(e))
TypeError: No matching overloads found. at native/common/jp_method.cpp:121
```

Is this from wrong syntax or bug?

**Comment by tdunning** [comment]
I think it is a bug. The problem is that the underlying software doesn't
understand a dict and thus I have to translate it into a cpp acceptable
data structure using OJAI primitives.

Ouch.

I will have to schedule this fix. We may have a new binding for python out
before I am able to get somebody to the fix. That is the good news. And the
bad news.

IF you want to take a stab, the data structure that needs to be built is
defined by the builder in OJAI. In Java, this looks like this:

DocumentBuilder x = org.ojai.json.Json.newDocumentBuilder()

This syntax is then reflected through to the python. I think that there
will be a fairly similar bit of code already in the bindings, but I am not
sure where.
